definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  standard__front_page:
    weight: -50
    menu_name: main
    parent: ''
    expanded: false
    enabled: true
  aggregator__feed_add:
    enabled: false
    menu_name: tools
    parent: ''
    expanded: false
    weight: 0
  aggregator__page_last:
    enabled: false
    menu_name: tools
    parent: ''
    weight: 5
    expanded: false
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
