module:
  action: 0
  aggregator: 0
  automated_cron: 0
  better_normalizers: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_filter: 0
  config_role_split: 0
  config_split: 0
  config_update: 0
  content_moderation: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  default_content: 0
  default_content_deploy: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity_reference_revisions: 0
  features: 0
  features_ui: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  inline_form_errors: 0
  link: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
  rules: 0
  s3fs: 0
  scheduler: 0
  scheduler_rules_integration: 0
  search: 0
  serialization: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  time_formatter: 0
  token: 0
  toolbar: 0
  tour: 0
  tour_ui: 0
  typed_data: 0
  update: 0
  user: 0
  uswds_paragraphs: 0
  views_ui: 0
  workflows: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  uswds: 0
  your_uswds_subtheme: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
